version: '3'

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #   - ./.env
    environment:
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_NAME=fastapi-db
      - DB_USERNAME=postgres
      - DB_PASSWD=12346-5
      - SECRET_KEY=86f661fb81f7c2c187b4e5ac33877296be506d75c377bfb30c64494c20591fb6
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINS=60

  postgres:
    image: postgres
    environment: 
    - POSTGRES_PASSWORD=123465
    - POSTGRES_DB=fastapi-db

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  