
name: Build and Deploy Code

on:
  push:
    branches:
      - "main"


jobs:
  job1:
    env:
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}} 
      DB_PORT: ${{secrets.DB_HOSTNAME}} 
      DB_NAME: ${{secrets.DB_NAME}} 
      DB_USERNAME: ${{secrets.DB_USERNAME}} 
      DB_PASSWD: ${{secrets.DB_PASSWD}} 
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}} 
      ACCESS_TOKEN_EXPIRE_MINS: ${{secrets.ACCESS_TOKEN_EXPIRE_MINS}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-intervals 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Test w/ pytest
        run: |
          pip install pytest
          pytest